//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 04:16:55 PM CEST 
//


package udir.types.eksamensplan;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EksamensdeltypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EksamensdeltypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Eksamen"/>
 *     &lt;enumeration value="Eksamen Del 1"/>
 *     &lt;enumeration value="Eksamen Del 2"/>
 *     &lt;enumeration value="Forberedelse"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EksamensdeltypeType")
@XmlEnum
public enum EksamensdeltypeType {

    @XmlEnumValue("Eksamen")
    EKSAMEN("Eksamen"),
    @XmlEnumValue("Eksamen Del 1")
    EKSAMEN_DEL_1("Eksamen Del 1"),
    @XmlEnumValue("Eksamen Del 2")
    EKSAMEN_DEL_2("Eksamen Del 2"),
    @XmlEnumValue("Forberedelse")
    FORBEREDELSE("Forberedelse");
    private final String value;

    EksamensdeltypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EksamensdeltypeType fromValue(String v) {
        for (EksamensdeltypeType c: EksamensdeltypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
