//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 04:16:55 PM CEST 
//


package udir.types.eksamensplan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EksamensdelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EksamensdelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{http://pas.udir.no/Eksamensplan}EksamensdeltypeType"/>
 *         &lt;element name="GjennomforingStart" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="GjennomforingStopp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Varighet" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EksamensdelType", propOrder = {
    "type",
    "gjennomforingStart",
    "gjennomforingStopp",
    "varighet"
})
public class EksamensdelType {

    @XmlElement(name = "Type", required = true)
    protected EksamensdeltypeType type;
    @XmlElement(name = "GjennomforingStart", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar gjennomforingStart;
    @XmlElement(name = "GjennomforingStopp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar gjennomforingStopp;
    @XmlElement(name = "Varighet")
    protected int varighet;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link EksamensdeltypeType }
     *     
     */
    public EksamensdeltypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link EksamensdeltypeType }
     *     
     */
    public void setType(EksamensdeltypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the gjennomforingStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGjennomforingStart() {
        return gjennomforingStart;
    }

    /**
     * Sets the value of the gjennomforingStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGjennomforingStart(XMLGregorianCalendar value) {
        this.gjennomforingStart = value;
    }

    /**
     * Gets the value of the gjennomforingStopp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGjennomforingStopp() {
        return gjennomforingStopp;
    }

    /**
     * Sets the value of the gjennomforingStopp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGjennomforingStopp(XMLGregorianCalendar value) {
        this.gjennomforingStopp = value;
    }

    /**
     * Gets the value of the varighet property.
     * 
     */
    public int getVarighet() {
        return varighet;
    }

    /**
     * Sets the value of the varighet property.
     * 
     */
    public void setVarighet(int value) {
        this.varighet = value;
    }

}
