//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 04:16:55 PM CEST 
//


package udir.types.eksamensplan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EksamensplanType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EksamensplanType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Opplaeringsniva" type="{http://pas.udir.no/CommonTypes}OpplaeringsnivaType"/>
 *         &lt;element name="Eksamensperiode" type="{http://pas.udir.no/Eksamensplan}EksamensperiodeType"/>
 *         &lt;element name="Eksamener" type="{http://pas.udir.no/Eksamensplan}EksamenerType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EksamensplanType", propOrder = {
    "opplaeringsniva",
    "eksamensperiode",
    "eksamener"
})
public class EksamensplanType {

    @XmlElement(name = "Opplaeringsniva", required = true)
    protected OpplaeringsnivaType opplaeringsniva;
    @XmlElement(name = "Eksamensperiode", required = true)
    protected EksamensperiodeType eksamensperiode;
    @XmlElement(name = "Eksamener", required = true)
    protected EksamenerType eksamener;

    /**
     * Gets the value of the opplaeringsniva property.
     * 
     * @return
     *     possible object is
     *     {@link OpplaeringsnivaType }
     *     
     */
    public OpplaeringsnivaType getOpplaeringsniva() {
        return opplaeringsniva;
    }

    /**
     * Sets the value of the opplaeringsniva property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpplaeringsnivaType }
     *     
     */
    public void setOpplaeringsniva(OpplaeringsnivaType value) {
        this.opplaeringsniva = value;
    }

    /**
     * Gets the value of the eksamensperiode property.
     * 
     * @return
     *     possible object is
     *     {@link EksamensperiodeType }
     *     
     */
    public EksamensperiodeType getEksamensperiode() {
        return eksamensperiode;
    }

    /**
     * Sets the value of the eksamensperiode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EksamensperiodeType }
     *     
     */
    public void setEksamensperiode(EksamensperiodeType value) {
        this.eksamensperiode = value;
    }

    /**
     * Gets the value of the eksamener property.
     * 
     * @return
     *     possible object is
     *     {@link EksamenerType }
     *     
     */
    public EksamenerType getEksamener() {
        return eksamener;
    }

    /**
     * Sets the value of the eksamener property.
     * 
     * @param value
     *     allowed object is
     *     {@link EksamenerType }
     *     
     */
    public void setEksamener(EksamenerType value) {
        this.eksamener = value;
    }

}
