//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 04:16:55 PM CEST 
//


package udir.types.eksamensplan;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the udir.types.eksamensplan package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: udir.types.eksamensplan
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EksamensplanResponse }
     * 
     */
    public EksamensplanResponse createEksamensplanResponse() {
        return new EksamensplanResponse();
    }

    /**
     * Create an instance of {@link EksamensplanerType }
     * 
     */
    public EksamensplanerType createEksamensplanerType() {
        return new EksamensplanerType();
    }

    /**
     * Create an instance of {@link EksamenType }
     * 
     */
    public EksamenType createEksamenType() {
        return new EksamenType();
    }

    /**
     * Create an instance of {@link EksamensplanType }
     * 
     */
    public EksamensplanType createEksamensplanType() {
        return new EksamensplanType();
    }

    /**
     * Create an instance of {@link EksamensperiodeType }
     * 
     */
    public EksamensperiodeType createEksamensperiodeType() {
        return new EksamensperiodeType();
    }

    /**
     * Create an instance of {@link EksamensdelType }
     * 
     */
    public EksamensdelType createEksamensdelType() {
        return new EksamensdelType();
    }

    /**
     * Create an instance of {@link EksamenerType }
     * 
     */
    public EksamenerType createEksamenerType() {
        return new EksamenerType();
    }

    /**
     * Create an instance of {@link EksamensdelerType }
     * 
     */
    public EksamensdelerType createEksamensdelerType() {
        return new EksamensdelerType();
    }

    /**
     * Create an instance of {@link KandidatgruppeansvarligType }
     * 
     */
    public KandidatgruppeansvarligType createKandidatgruppeansvarligType() {
        return new KandidatgruppeansvarligType();
    }

    /**
     * Create an instance of {@link KandidatgruppeansvarligeType }
     * 
     */
    public KandidatgruppeansvarligeType createKandidatgruppeansvarligeType() {
        return new KandidatgruppeansvarligeType();
    }

}
