//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 04:18:21 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2000/09/xmldsig#", 
xmlns = {		
		@XmlNs(namespaceURI = "http://pas.udir.no/ClientIdentification", prefix = "ci"),
		@XmlNs(namespaceURI = "http://www.w3.org/2000/09/xmldsig#", prefix="ds")
	},
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

package udir.types.clientidentification;
import javax.xml.bind.annotation.XmlNs;
