//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 06:07:12 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema( namespace = "http://pas.udir.no/Eksamensplan",
		xmlns = { 
			@XmlNs(namespaceURI = "http://pas.udir.no/Pamelding", prefix = "pa"),
			@XmlNs(namespaceURI = "http://pas.udir.no/Eksamensplan", prefix = "ep"),
			@XmlNs(namespaceURI = "http://pas.udir.no/CommonTypes", prefix = "ct"),
			@XmlNs(namespaceURI = "http://pas.udir.no/ClientIdentification", prefix = "ci")
		}, 
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

package udir.types;

import javax.xml.bind.annotation.XmlNs;
