//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 04:16:59 PM CEST 
//


package udir.types.pamelding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KandidatgruppeReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KandidatgruppeReportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Navn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Fagkode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Kandidatgruppeansvarlige" type="{http://pas.udir.no/Pamelding}KandidatgruppeansvarligReportsType"/>
 *         &lt;element name="Kandidater" type="{http://pas.udir.no/Pamelding}KandidatReportsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KandidatgruppeReportType", propOrder = {
    "navn",
    "fagkode",
    "kandidatgruppeansvarlige",
    "kandidater"
})
public class KandidatgruppeReportType {

    @XmlElement(name = "Navn", required = true, nillable = true)
    protected String navn;
    @XmlElement(name = "Fagkode", required = true)
    protected String fagkode;
    @XmlElement(name = "Kandidatgruppeansvarlige", required = true, nillable = true)
    protected KandidatgruppeansvarligReportsType kandidatgruppeansvarlige;
    @XmlElement(name = "Kandidater", required = true, nillable = true)
    protected KandidatReportsType kandidater;

    /**
     * Gets the value of the navn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavn() {
        return navn;
    }

    /**
     * Sets the value of the navn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavn(String value) {
        this.navn = value;
    }

    /**
     * Gets the value of the fagkode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFagkode() {
        return fagkode;
    }

    /**
     * Sets the value of the fagkode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFagkode(String value) {
        this.fagkode = value;
    }

    /**
     * Gets the value of the kandidatgruppeansvarlige property.
     * 
     * @return
     *     possible object is
     *     {@link KandidatgruppeansvarligReportsType }
     *     
     */
    public KandidatgruppeansvarligReportsType getKandidatgruppeansvarlige() {
        return kandidatgruppeansvarlige;
    }

    /**
     * Sets the value of the kandidatgruppeansvarlige property.
     * 
     * @param value
     *     allowed object is
     *     {@link KandidatgruppeansvarligReportsType }
     *     
     */
    public void setKandidatgruppeansvarlige(KandidatgruppeansvarligReportsType value) {
        this.kandidatgruppeansvarlige = value;
    }

    /**
     * Gets the value of the kandidater property.
     * 
     * @return
     *     possible object is
     *     {@link KandidatReportsType }
     *     
     */
    public KandidatReportsType getKandidater() {
        return kandidater;
    }

    /**
     * Sets the value of the kandidater property.
     * 
     * @param value
     *     allowed object is
     *     {@link KandidatReportsType }
     *     
     */
    public void setKandidater(KandidatReportsType value) {
        this.kandidater = value;
    }

}
