//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 04:16:59 PM CEST 
//


package udir.types.pamelding;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the udir.types.pamelding package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: udir.types.pamelding
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PameldingReport }
     * 
     */
    public PameldingReport createPameldingReport() {
        return new PameldingReport();
    }

    /**
     * Create an instance of {@link KandidatgruppeReportsType }
     * 
     */
    public KandidatgruppeReportsType createKandidatgruppeReportsType() {
        return new KandidatgruppeReportsType();
    }

    /**
     * Create an instance of {@link PameldteKandidater }
     * 
     */
    public PameldteKandidater createPameldteKandidater() {
        return new PameldteKandidater();
    }

    /**
     * Create an instance of {@link EksamenspameldingerType }
     * 
     */
    public EksamenspameldingerType createEksamenspameldingerType() {
        return new EksamenspameldingerType();
    }

    /**
     * Create an instance of {@link Pamelding }
     * 
     */
    public Pamelding createPamelding() {
        return new Pamelding();
    }

    /**
     * Create an instance of {@link KandidatgrupperType }
     * 
     */
    public KandidatgrupperType createKandidatgrupperType() {
        return new KandidatgrupperType();
    }

    /**
     * Create an instance of {@link ApiError }
     * 
     */
    public ApiError createApiError() {
        return new ApiError();
    }

    /**
     * Create an instance of {@link PameldingReference }
     * 
     */
    public PameldingReference createPameldingReference() {
        return new PameldingReference();
    }

    /**
     * Create an instance of {@link PameldteKandidatgrupperType }
     * 
     */
    public PameldteKandidatgrupperType createPameldteKandidatgrupperType() {
        return new PameldteKandidatgrupperType();
    }

    /**
     * Create an instance of {@link KandidatgruppeansvarligReportsType }
     * 
     */
    public KandidatgruppeansvarligReportsType createKandidatgruppeansvarligReportsType() {
        return new KandidatgruppeansvarligReportsType();
    }

    /**
     * Create an instance of {@link KandidatgruppeType }
     * 
     */
    public KandidatgruppeType createKandidatgruppeType() {
        return new KandidatgruppeType();
    }

    /**
     * Create an instance of {@link EksamenspameldingType }
     * 
     */
    public EksamenspameldingType createEksamenspameldingType() {
        return new EksamenspameldingType();
    }

    /**
     * Create an instance of {@link KandidatgruppeReportType }
     * 
     */
    public KandidatgruppeReportType createKandidatgruppeReportType() {
        return new KandidatgruppeReportType();
    }

    /**
     * Create an instance of {@link KandidatType }
     * 
     */
    public KandidatType createKandidatType() {
        return new KandidatType();
    }

    /**
     * Create an instance of {@link KandidatReportType }
     * 
     */
    public KandidatReportType createKandidatReportType() {
        return new KandidatReportType();
    }

    /**
     * Create an instance of {@link KandidaterType }
     * 
     */
    public KandidaterType createKandidaterType() {
        return new KandidaterType();
    }

    /**
     * Create an instance of {@link KandidatgruppeansvarligReportType }
     * 
     */
    public KandidatgruppeansvarligReportType createKandidatgruppeansvarligReportType() {
        return new KandidatgruppeansvarligReportType();
    }

    /**
     * Create an instance of {@link KandidatReportsType }
     * 
     */
    public KandidatReportsType createKandidatReportsType() {
        return new KandidatReportsType();
    }

    /**
     * Create an instance of {@link PameldtKandidatgruppeType }
     * 
     */
    public PameldtKandidatgruppeType createPameldtKandidatgruppeType() {
        return new PameldtKandidatgruppeType();
    }

    /**
     * Create an instance of {@link PameldtKandidatType }
     * 
     */
    public PameldtKandidatType createPameldtKandidatType() {
        return new PameldtKandidatType();
    }

    /**
     * Create an instance of {@link PameldteKandidaterType }
     * 
     */
    public PameldteKandidaterType createPameldteKandidaterType() {
        return new PameldteKandidaterType();
    }

    /**
     * Create an instance of {@link KandidatgruppeansvarligType }
     * 
     */
    public KandidatgruppeansvarligType createKandidatgruppeansvarligType() {
        return new KandidatgruppeansvarligType();
    }

    /**
     * Create an instance of {@link KandidatgruppeansvarligeType }
     * 
     */
    public KandidatgruppeansvarligeType createKandidatgruppeansvarligeType() {
        return new KandidatgruppeansvarligeType();
    }

}
