//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 04:16:59 PM CEST 
//


package udir.types.pamelding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Eksamensperiodekode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Eksamenspameldinger" type="{http://pas.udir.no/Pamelding}EksamenspameldingerType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eksamensperiodekode",
    "eksamenspameldinger"
})
@XmlRootElement(name = "PameldteKandidater")
public class PameldteKandidater {

    @XmlElement(name = "Eksamensperiodekode", namespace = "", required = true)
    protected String eksamensperiodekode;
    @XmlElement(name = "Eksamenspameldinger", namespace = "", required = true)
    protected EksamenspameldingerType eksamenspameldinger;

    /**
     * Gets the value of the eksamensperiodekode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEksamensperiodekode() {
        return eksamensperiodekode;
    }

    /**
     * Sets the value of the eksamensperiodekode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEksamensperiodekode(String value) {
        this.eksamensperiodekode = value;
    }

    /**
     * Gets the value of the eksamenspameldinger property.
     * 
     * @return
     *     possible object is
     *     {@link EksamenspameldingerType }
     *     
     */
    public EksamenspameldingerType getEksamenspameldinger() {
        return eksamenspameldinger;
    }

    /**
     * Sets the value of the eksamenspameldinger property.
     * 
     * @param value
     *     allowed object is
     *     {@link EksamenspameldingerType }
     *     
     */
    public void setEksamenspameldinger(EksamenspameldingerType value) {
        this.eksamenspameldinger = value;
    }

}
