//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 04:16:59 PM CEST 
//


package udir.types.pamelding;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SprakType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SprakType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Bokmal"/>
 *     &lt;enumeration value="Nynorsk"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SprakType", namespace = "http://pas.udir.no/CommonTypes")
@XmlEnum
public enum SprakType {

    @XmlEnumValue("Bokmal")
    BOKMAL("Bokmal"),
    @XmlEnumValue("Nynorsk")
    NYNORSK("Nynorsk");
    private final String value;

    SprakType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SprakType fromValue(String v) {
        for (SprakType c: SprakType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
