//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 04:16:55 PM CEST 
//


package udir.types.eksamensplan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Eksamensplaner" type="{http://pas.udir.no/Eksamensplan}EksamensplanerType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eksamensplaner"
})
@XmlRootElement(name = "EksamensplanResponse")
public class EksamensplanResponse {

    @XmlElement(name = "Eksamensplaner", required = true, nillable = true)
    protected EksamensplanerType eksamensplaner;

    /**
     * Gets the value of the eksamensplaner property.
     * 
     * @return
     *     possible object is
     *     {@link EksamensplanerType }
     *     
     */
    public EksamensplanerType getEksamensplaner() {
        return eksamensplaner;
    }

    /**
     * Sets the value of the eksamensplaner property.
     * 
     * @param value
     *     allowed object is
     *     {@link EksamensplanerType }
     *     
     */
    public void setEksamensplaner(EksamensplanerType value) {
        this.eksamensplaner = value;
    }

}
