//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 04:16:55 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pas.udir.no/Eksamensplan", 
xmlns = {		
		@XmlNs(namespaceURI = "http://pas.udir.no/Eksamensplan", prefix = "ep"),
		@XmlNs(namespaceURI = "http://pas.udir.no/CommonTypes", prefix = "ct")		
	},
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package udir.types.eksamensplan;

import javax.xml.bind.annotation.XmlNs;
