//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 04:16:59 PM CEST 
//


package udir.types.pamelding;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KandidatStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="KandidatStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="IkkeStartet"/>
 *     &lt;enumeration value="Pameldt"/>
 *     &lt;enumeration value="IkkePameldt"/>
 *     &lt;enumeration value="DelvisPameldt"/>
 *     &lt;enumeration value="PameldtAnnenSkole"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "KandidatStatusType")
@XmlEnum
public enum KandidatStatusType {

    @XmlEnumValue("IkkeStartet")
    IKKE_STARTET("IkkeStartet"),
    @XmlEnumValue("Pameldt")
    PAMELDT("Pameldt"),
    @XmlEnumValue("IkkePameldt")
    IKKE_PAMELDT("IkkePameldt"),
    @XmlEnumValue("DelvisPameldt")
    DELVIS_PAMELDT("DelvisPameldt"),
    @XmlEnumValue("PameldtAnnenSkole")
    PAMELDT_ANNEN_SKOLE("PameldtAnnenSkole");
    private final String value;

    KandidatStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static KandidatStatusType fromValue(String v) {
        for (KandidatStatusType c: KandidatStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
