//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 04:16:59 PM CEST 
//


package udir.types.pamelding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Orgnr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Skolenavn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Kandidatgrupper" type="{http://pas.udir.no/Pamelding}KandidatgruppeReportsType"/>
 *         &lt;element name="Status" type="{http://pas.udir.no/Pamelding}PameldingsStatusType"/>
 *         &lt;element name="StatusMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Eksamensperiode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Opplaeringsniva" type="{http://pas.udir.no/CommonTypes}OpplaeringsnivaType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orgnr",
    "skolenavn",
    "kandidatgrupper",
    "status",
    "statusMessage",
    "eksamensperiode",
    "opplaeringsniva"
})
@XmlRootElement(name = "PameldingReport")
public class PameldingReport {

    @XmlElement(name = "Orgnr", required = true)
    protected String orgnr;
    @XmlElement(name = "Skolenavn", required = true)
    protected String skolenavn;
    @XmlElement(name = "Kandidatgrupper", required = true, nillable = true)
    protected KandidatgruppeReportsType kandidatgrupper;
    @XmlElement(name = "Status", required = true)
    protected PameldingsStatusType status;
    @XmlElement(name = "StatusMessage", required = true, nillable = true)
    protected String statusMessage;
    @XmlElement(name = "Eksamensperiode", required = true, nillable = true)
    protected String eksamensperiode;
    @XmlElement(name = "Opplaeringsniva", required = true)
    protected OpplaeringsnivaType opplaeringsniva;

    /**
     * Gets the value of the orgnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgnr() {
        return orgnr;
    }

    /**
     * Sets the value of the orgnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgnr(String value) {
        this.orgnr = value;
    }

    /**
     * Gets the value of the skolenavn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkolenavn() {
        return skolenavn;
    }

    /**
     * Sets the value of the skolenavn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkolenavn(String value) {
        this.skolenavn = value;
    }

    /**
     * Gets the value of the kandidatgrupper property.
     * 
     * @return
     *     possible object is
     *     {@link KandidatgruppeReportsType }
     *     
     */
    public KandidatgruppeReportsType getKandidatgrupper() {
        return kandidatgrupper;
    }

    /**
     * Sets the value of the kandidatgrupper property.
     * 
     * @param value
     *     allowed object is
     *     {@link KandidatgruppeReportsType }
     *     
     */
    public void setKandidatgrupper(KandidatgruppeReportsType value) {
        this.kandidatgrupper = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link PameldingsStatusType }
     *     
     */
    public PameldingsStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link PameldingsStatusType }
     *     
     */
    public void setStatus(PameldingsStatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the statusMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusMessage() {
        return statusMessage;
    }

    /**
     * Sets the value of the statusMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusMessage(String value) {
        this.statusMessage = value;
    }

    /**
     * Gets the value of the eksamensperiode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEksamensperiode() {
        return eksamensperiode;
    }

    /**
     * Sets the value of the eksamensperiode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEksamensperiode(String value) {
        this.eksamensperiode = value;
    }

    /**
     * Gets the value of the opplaeringsniva property.
     * 
     * @return
     *     possible object is
     *     {@link OpplaeringsnivaType }
     *     
     */
    public OpplaeringsnivaType getOpplaeringsniva() {
        return opplaeringsniva;
    }

    /**
     * Sets the value of the opplaeringsniva property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpplaeringsnivaType }
     *     
     */
    public void setOpplaeringsniva(OpplaeringsnivaType value) {
        this.opplaeringsniva = value;
    }

}
