//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 04:16:59 PM CEST 
//


package udir.types.pamelding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PameldtKandidatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PameldtKandidatType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Fodselsnr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Fornavn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Etternavn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Malform" type="{http://pas.udir.no/CommonTypes}SprakType"/>
 *         &lt;element name="Kandidattype" type="{http://pas.udir.no/CommonTypes}KandidattypeType"/>
 *         &lt;element name="Kandidatnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PameldtKandidatType", propOrder = {
    "fodselsnr",
    "fornavn",
    "etternavn",
    "malform",
    "kandidattype",
    "kandidatnummer"
})
public class PameldtKandidatType {

    @XmlElement(name = "Fodselsnr", namespace = "", required = true)
    protected String fodselsnr;
    @XmlElement(name = "Fornavn", namespace = "", required = true)
    protected String fornavn;
    @XmlElement(name = "Etternavn", namespace = "", required = true)
    protected String etternavn;
    @XmlElement(name = "Malform", namespace = "", required = true, nillable = true)
    protected SprakType malform;
    @XmlElement(name = "Kandidattype", namespace = "", required = true)
    protected KandidattypeType kandidattype;
    @XmlElement(name = "Kandidatnummer", namespace = "", required = true)
    protected String kandidatnummer;

    /**
     * Gets the value of the fodselsnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFodselsnr() {
        return fodselsnr;
    }

    /**
     * Sets the value of the fodselsnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFodselsnr(String value) {
        this.fodselsnr = value;
    }

    /**
     * Gets the value of the fornavn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFornavn() {
        return fornavn;
    }

    /**
     * Sets the value of the fornavn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFornavn(String value) {
        this.fornavn = value;
    }

    /**
     * Gets the value of the etternavn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEtternavn() {
        return etternavn;
    }

    /**
     * Sets the value of the etternavn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEtternavn(String value) {
        this.etternavn = value;
    }

    /**
     * Gets the value of the malform property.
     * 
     * @return
     *     possible object is
     *     {@link SprakType }
     *     
     */
    public SprakType getMalform() {
        return malform;
    }

    /**
     * Sets the value of the malform property.
     * 
     * @param value
     *     allowed object is
     *     {@link SprakType }
     *     
     */
    public void setMalform(SprakType value) {
        this.malform = value;
    }

    /**
     * Gets the value of the kandidattype property.
     * 
     * @return
     *     possible object is
     *     {@link KandidattypeType }
     *     
     */
    public KandidattypeType getKandidattype() {
        return kandidattype;
    }

    /**
     * Sets the value of the kandidattype property.
     * 
     * @param value
     *     allowed object is
     *     {@link KandidattypeType }
     *     
     */
    public void setKandidattype(KandidattypeType value) {
        this.kandidattype = value;
    }

    /**
     * Gets the value of the kandidatnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKandidatnummer() {
        return kandidatnummer;
    }

    /**
     * Sets the value of the kandidatnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKandidatnummer(String value) {
        this.kandidatnummer = value;
    }

}
