//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 04:16:59 PM CEST 
//


package udir.types.pamelding;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PameldingsStatusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PameldingsStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="IkkeStartet"/>
 *     &lt;enumeration value="Startet"/>
 *     &lt;enumeration value="Ferdig"/>
 *     &lt;enumeration value="Feilet"/>
 *     &lt;enumeration value="DelvisFerdig"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PameldingsStatusType")
@XmlEnum
public enum PameldingsStatusType {

    @XmlEnumValue("IkkeStartet")
    IKKE_STARTET("IkkeStartet"),
    @XmlEnumValue("Startet")
    STARTET("Startet"),
    @XmlEnumValue("Ferdig")
    FERDIG("Ferdig"),
    @XmlEnumValue("Feilet")
    FEILET("Feilet"),
    @XmlEnumValue("DelvisFerdig")
    DELVIS_FERDIG("DelvisFerdig");
    private final String value;

    PameldingsStatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PameldingsStatusType fromValue(String v) {
        for (PameldingsStatusType c: PameldingsStatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
